-- Development site, advance booking, and document vault updates
-- Note: no ALTER is required to replace "Site ID" with "Site Name" in the UI.
-- The application now resolves and auto-creates development_sites by name,
-- while still storing development_entries.site_id as the normalized foreign key.

ALTER TABLE advance_bookings
  ADD COLUMN IF NOT EXISTS seller_name VARCHAR(180) NULL AFTER customer_name,
  ADD KEY idx_bookings_seller (seller_name);

ALTER TABLE development_entries
  ADD COLUMN IF NOT EXISTS jcb_number VARCHAR(120) NULL AFTER site_id,
  ADD COLUMN IF NOT EXISTS tractor_number VARCHAR(120) NULL AFTER jcb_number,
  ADD COLUMN IF NOT EXISTS damper_number VARCHAR(120) NULL AFTER tractor_number,
  ADD COLUMN IF NOT EXISTS owner_name VARCHAR(180) NULL AFTER damper_number,
  ADD COLUMN IF NOT EXISTS driver_name VARCHAR(180) NULL AFTER owner_name,
  ADD COLUMN IF NOT EXISTS mobile_number VARCHAR(32) NULL AFTER driver_name,
  ADD COLUMN IF NOT EXISTS rent_type VARCHAR(32) NULL AFTER mobile_number,
  ADD COLUMN IF NOT EXISTS amount_mode VARCHAR(32) NULL AFTER rent_type,
  ADD COLUMN IF NOT EXISTS start_date DATE NULL AFTER amount_mode,
  ADD COLUMN IF NOT EXISTS end_date DATE NULL AFTER start_date,
  ADD COLUMN IF NOT EXISTS start_time TIME NULL AFTER end_date,
  ADD COLUMN IF NOT EXISTS stop_time TIME NULL AFTER start_time,
  ADD COLUMN IF NOT EXISTS total_days DECIMAL(10,2) NOT NULL DEFAULT 0 AFTER stop_time,
  ADD COLUMN IF NOT EXISTS total_hours DECIMAL(10,2) NOT NULL DEFAULT 0 AFTER total_days,
  ADD COLUMN IF NOT EXISTS total_trips INT UNSIGNED NOT NULL DEFAULT 0 AFTER total_hours,
  ADD COLUMN IF NOT EXISTS rate_per_day DECIMAL(14,2) NOT NULL DEFAULT 0 AFTER total_trips,
  ADD COLUMN IF NOT EXISTS rate_per_hour DECIMAL(14,2) NOT NULL DEFAULT 0 AFTER rate_per_day,
  ADD COLUMN IF NOT EXISTS rate_per_trip DECIMAL(14,2) NOT NULL DEFAULT 0 AFTER rate_per_hour,
  ADD COLUMN IF NOT EXISTS advance_diesel DECIMAL(14,2) NOT NULL DEFAULT 0 AFTER rate_per_trip,
  ADD COLUMN IF NOT EXISTS diesel_given DECIMAL(14,2) NOT NULL DEFAULT 0 AFTER advance_diesel,
  ADD COLUMN IF NOT EXISTS diesel_cost DECIMAL(14,2) NOT NULL DEFAULT 0 AFTER diesel_given,
  ADD COLUMN IF NOT EXISTS advance_paid DECIMAL(14,2) NOT NULL DEFAULT 0 AFTER diesel_cost,
  ADD COLUMN IF NOT EXISTS remaining_amount DECIMAL(14,2) NOT NULL DEFAULT 0 AFTER advance_paid,
  ADD COLUMN IF NOT EXISTS payment_status VARCHAR(32) NOT NULL DEFAULT 'pending' AFTER remaining_amount,
  MODIFY COLUMN work_type VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS construction_material VARCHAR(180) NULL AFTER work_type,
  ADD COLUMN IF NOT EXISTS work_location VARCHAR(255) NULL AFTER construction_material,
  ADD COLUMN IF NOT EXISTS gps_location VARCHAR(255) NULL AFTER work_location,
  ADD COLUMN IF NOT EXISTS loading_point VARCHAR(255) NULL AFTER gps_location,
  ADD COLUMN IF NOT EXISTS unloading_point VARCHAR(255) NULL AFTER loading_point,
  ADD COLUMN IF NOT EXISTS work_description TEXT NULL AFTER unloading_point,
  ADD COLUMN IF NOT EXISTS working_photo_url VARCHAR(500) NULL AFTER work_description,
  ADD COLUMN IF NOT EXISTS before_photo_url VARCHAR(500) NULL AFTER working_photo_url,
  ADD COLUMN IF NOT EXISTS after_photo_url VARCHAR(500) NULL AFTER before_photo_url,
  ADD COLUMN IF NOT EXISTS signature_url VARCHAR(500) NULL AFTER after_photo_url,
  MODIFY COLUMN description TEXT NULL,
  ADD KEY idx_development_entries_category (category),
  ADD KEY idx_development_entries_payment (payment_status);

ALTER TABLE document_folders
  ADD COLUMN IF NOT EXISTS folder_code VARCHAR(64) NULL AFTER project_id,
  ADD COLUMN IF NOT EXISTS folder_label VARCHAR(255) NULL AFTER folder_code,
  ADD COLUMN IF NOT EXISTS plot_number VARCHAR(120) NULL AFTER folder_label,
  ADD COLUMN IF NOT EXISTS buyer_name VARCHAR(180) NULL AFTER plot_number,
  ADD COLUMN IF NOT EXISTS buyer_mobile_number VARCHAR(32) NULL AFTER buyer_name,
  ADD COLUMN IF NOT EXISTS buyer_aadhaar_number VARCHAR(32) NULL AFTER buyer_mobile_number,
  ADD COLUMN IF NOT EXISTS buyer_pan_number VARCHAR(32) NULL AFTER buyer_aadhaar_number,
  ADD COLUMN IF NOT EXISTS seller_name VARCHAR(180) NULL AFTER buyer_pan_number,
  ADD COLUMN IF NOT EXISTS seller_mobile_number VARCHAR(32) NULL AFTER seller_name,
  ADD COLUMN IF NOT EXISTS seller_aadhaar_number VARCHAR(32) NULL AFTER seller_mobile_number,
  ADD COLUMN IF NOT EXISTS seller_pan_number VARCHAR(32) NULL AFTER seller_aadhaar_number,
  ADD COLUMN IF NOT EXISTS witness_1_name VARCHAR(180) NULL AFTER seller_pan_number,
  ADD COLUMN IF NOT EXISTS witness_1_aadhaar_number VARCHAR(32) NULL AFTER witness_1_name,
  ADD COLUMN IF NOT EXISTS witness_2_name VARCHAR(180) NULL AFTER witness_1_aadhaar_number,
  ADD COLUMN IF NOT EXISTS witness_2_aadhaar_number VARCHAR(32) NULL AFTER witness_2_name,
  ADD COLUMN IF NOT EXISTS identifier_name VARCHAR(180) NULL AFTER witness_2_aadhaar_number,
  ADD COLUMN IF NOT EXISTS identifier_mobile_number VARCHAR(32) NULL AFTER identifier_name,
  ADD COLUMN IF NOT EXISTS identifier_aadhaar_number VARCHAR(32) NULL AFTER identifier_mobile_number,
  ADD COLUMN IF NOT EXISTS print_layout VARCHAR(32) NOT NULL DEFAULT 'a4' AFTER identifier_aadhaar_number,
  ADD COLUMN IF NOT EXISTS aadhaar_layout VARCHAR(32) NOT NULL DEFAULT 'single-page' AFTER print_layout,
  ADD COLUMN IF NOT EXISTS page_orientation VARCHAR(16) NOT NULL DEFAULT 'portrait' AFTER aadhaar_layout,
  ADD COLUMN IF NOT EXISTS dpi_quality VARCHAR(32) NOT NULL DEFAULT 'standard' AFTER page_orientation,
  ADD COLUMN IF NOT EXISTS color_mode VARCHAR(32) NOT NULL DEFAULT 'color' AFTER dpi_quality,
  ADD COLUMN IF NOT EXISTS export_type VARCHAR(32) NOT NULL DEFAULT 'pdf' AFTER color_mode,
  ADD COLUMN IF NOT EXISTS admin_lock TINYINT(1) NOT NULL DEFAULT 0 AFTER export_type,
  ADD COLUMN IF NOT EXISTS is_hidden TINYINT(1) NOT NULL DEFAULT 0 AFTER admin_lock,
  ADD UNIQUE KEY ux_document_folders_code (folder_code),
  ADD KEY idx_document_folders_plot (plot_number),
  ADD KEY idx_document_folders_buyer_mobile (buyer_mobile_number),
  ADD KEY idx_document_folders_buyer_aadhaar (buyer_aadhaar_number);

ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS section VARCHAR(64) NULL AFTER folder_id,
  ADD COLUMN IF NOT EXISTS party_name VARCHAR(180) NULL AFTER section,
  ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0 AFTER party_name,
  ADD KEY idx_documents_section (section);
