import { festivalStyles } from "@/lib/brand";
import type { ModuleConfig, ModuleSlug, SelectOption } from "@/lib/types";

const roleOptions: SelectOption[] = [
  { label: "Admin", value: "admin" },
  { label: "Agent", value: "agent" },
  { label: "Accountant", value: "accountant" },
  { label: "Engineer", value: "engineer" },
];

const statusOptions: SelectOption[] = [
  { label: "Active", value: "active" },
  { label: "Inactive", value: "inactive" },
];

const paymentModeOptions: SelectOption[] = [
  { label: "GPay", value: "GPay" },
  { label: "PhonePe", value: "PhonePe" },
  { label: "Cash", value: "Cash" },
  { label: "Bank", value: "Bank" },
];

const gstBillOptions: SelectOption[] = [
  { label: "GST Bill", value: "gst" },
  { label: "Non-GST Bill", value: "non-gst" },
];

const paymentStatusOptions: SelectOption[] = [
  { label: "Paid", value: "paid" },
  { label: "Partial", value: "partial" },
  { label: "Pending", value: "pending" },
];

const tractorRentOptions: SelectOption[] = [
  { label: "Daily Rent", value: "daily" },
  { label: "Hourly Rent", value: "hourly" },
];

const damperAmountModeOptions: SelectOption[] = [
  { label: "Per Trip", value: "per_trip" },
  { label: "Per Hour", value: "per_hour" },
  { label: "Daily Rent", value: "daily" },
];

const documentPrintLayoutOptions: SelectOption[] = [
  { label: "A4 Size", value: "a4" },
  { label: "Legal Size", value: "legal" },
  { label: "Half Page", value: "half-page" },
  { label: "Full Page", value: "full-page" },
];

const documentAadhaarLayoutOptions: SelectOption[] = [
  { label: "One Aadhaar / Page", value: "single-page" },
  { label: "Front + Back One Page", value: "front-back" },
  { label: "Two Aadhaar / Page", value: "two-per-page" },
  { label: "Four Documents Grid", value: "four-grid" },
];

const pageOrientationOptions: SelectOption[] = [
  { label: "Portrait", value: "portrait" },
  { label: "Landscape", value: "landscape" },
];

const dpiQualityOptions: SelectOption[] = [
  { label: "Standard", value: "standard" },
  { label: "High", value: "high" },
  { label: "Print Ready", value: "print-ready" },
];

const exportTypeOptions: SelectOption[] = [
  { label: "PDF", value: "pdf" },
  { label: "Image", value: "image" },
  { label: "Print Direct", value: "print" },
  { label: "WhatsApp Share", value: "whatsapp" },
];

export const moduleCatalog: ModuleConfig[] = [
  {
    slug: "users",
    section: "Access",
    title: "User Management",
    subtitle: "Admin, agent, accountant, and engineer accounts with secure access control.",
    badge: "Login and role system",
    accent: "bg-black text-white",
    icon: "Shield",
    resource: "users",
    fields: [
      { key: "full_name", label: "Full name", type: "text", required: true },
      { key: "email", label: "Email", type: "email", required: true },
      { key: "phone", label: "Phone", type: "tel" },
      { key: "role", label: "Role", type: "select", options: roleOptions, required: true },
      { key: "password", label: "Password", type: "password", required: true },
      { key: "status", label: "Status", type: "select", options: statusOptions },
    ],
    columns: [
      { key: "full_name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "role", label: "Role", type: "badge" },
      { key: "phone", label: "Phone" },
      { key: "status", label: "Status", type: "badge" },
      { key: "created_at", label: "Created", type: "date" },
    ],
    summaries: [
      { label: "Users", type: "count", tone: "accent" },
      { label: "Roles", type: "unique", field: "role" },
    ],
    emptyState: "Create the first operator profile to start role-based access.",
  },
  {
    slug: "projects",
    section: "Sales",
    title: "Project Register",
    subtitle: "Master list for layouts, sites, and construction-linked properties.",
    badge: "Top project tracking",
    accent: "bg-accent text-white",
    icon: "Building2",
    resource: "projects",
    fields: [
      { key: "name", label: "Project name", type: "text", required: true },
      { key: "code", label: "Project code", type: "text", required: true },
      {
        key: "type",
        label: "Type",
        type: "select",
        required: true,
        options: [
          { label: "Plot", value: "plot" },
          { label: "Construction", value: "construction" },
          { label: "Development", value: "development" },
          { label: "Mixed", value: "mixed" },
        ],
      },
      { key: "village", label: "Village", type: "text" },
      { key: "location", label: "Location", type: "text" },
      { key: "status", label: "Status", type: "select", options: statusOptions },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      { key: "name", label: "Project" },
      { key: "type", label: "Type", type: "badge" },
      { key: "village", label: "Village" },
      { key: "location", label: "Location" },
      { key: "status", label: "Status", type: "badge" },
    ],
    summaries: [
      { label: "Projects", type: "count", tone: "accent" },
      { label: "Villages", type: "unique", field: "village" },
    ],
    emptyState: "Add projects to organize plots, bookings, and site reports.",
  },
  {
    slug: "plots",
    section: "Sales",
    title: "Plot Management",
    subtitle: "Inventory with village, survey number, area, price, and availability status.",
    badge: "Plot inventory",
    accent: "bg-white text-black",
    icon: "MapPinned",
    resource: "plots",
    fields: [
      { key: "project_id", label: "Project Info", type: "project_select", required: true },
      { key: "village", label: "Village", type: "text", required: true },
      { key: "survey_number", label: "Survey number", type: "text", required: true },
      { key: "area_sqft", label: "Area (sq.ft.)", type: "number", step: "0.01", required: true },
      { key: "price", label: "Price", type: "number", step: "0.01", required: true },
      { key: "location_text", label: "Location", type: "text" },
      { key: "map_url", label: "Map URL", type: "text" },
      {
        key: "status",
        label: "Availability",
        type: "select",
        options: [
          { label: "Available", value: "available" },
          { label: "Sold", value: "sold" },
          { label: "Blocked", value: "blocked" },
        ],
      },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      { key: "village", label: "Village" },
      { key: "survey_number", label: "Survey No." },
      { key: "area_sqft", label: "Area", type: "number" },
      { key: "price", label: "Price", type: "currency" },
      { key: "status", label: "Status", type: "badge" },
    ],
    summaries: [
      { label: "Plots", type: "count", tone: "accent" },
      { label: "Inventory", type: "sum", field: "price", prefix: "₹" },
    ],
    emptyState: "Add plot records before sales, bookings, or purchase agreements.",
  },
  {
    slug: "transactions",
    section: "Sales",
    title: "Buy / Sell Transactions",
    subtitle: "Purchase and sale entries with payment modes, GST, and profit or loss visibility.",
    badge: "Auto P&L",
    accent: "bg-black text-white",
    icon: "Handshake",
    resource: "transactions",
    fields: [
      {
        key: "transaction_type",
        label: "Entry type",
        type: "select",
        required: true,
        options: [
          { label: "Sale", value: "sale" },
          { label: "Purchase", value: "purchase" },
        ],
      },
      { key: "project_id", label: "Project Info", type: "project_select", required: true },
      { key: "plot_id", label: "Plot ID", type: "number", step: "1" },
      { key: "counterparty_name", label: "Buyer / Seller name", type: "text", required: true },
      { key: "counterparty_phone", label: "Phone", type: "tel" },
      { key: "counterparty_email", label: "Email", type: "email" },
      { key: "counterparty_photo_url", label: "Photo / Image", type: "image" },
      { key: "counterparty_signature_url", label: "Signature Image", type: "image" },
      { key: "village", label: "Village", type: "text", required: true },
      { key: "survey_number", label: "Survey number", type: "text", required: true },
      { key: "area_sqft", label: "Area (sq.ft.)", type: "number", step: "0.01" },
      { key: "payment_mode", label: "Payment mode", type: "select", options: paymentModeOptions },
      { key: "base_amount", label: "Base amount", type: "number", step: "0.01", required: true },
      { key: "expense_amount", label: "Cost / expense", type: "number", step: "0.01" },
      { key: "gst_enabled", label: "GST enabled", type: "checkbox" },
      { key: "gst_rate", label: "GST rate (%)", type: "number", step: "0.01" },
      { key: "transacted_at", label: "Transaction date & time", type: "datetime-local" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      { key: "transaction_type", label: "Type", type: "badge" },
      { key: "counterparty_name", label: "Party" },
      { key: "village", label: "Village" },
      { key: "payment_mode", label: "Mode" },
      { key: "total_amount", label: "Total", type: "currency" },
      { key: "profit_loss", label: "Profit / Loss", type: "currency" },
    ],
    summaries: [
      { label: "Entries", type: "count", tone: "accent" },
      { label: "Turnover", type: "sum", field: "total_amount", prefix: "₹" },
    ],
    emptyState: "Record sales and purchases to activate profitability reporting.",
  },
  {
    slug: "money-transactions",
    section: "Finance",
    title: "Transaction Management",
    subtitle: "Income, Expense, Lent, and Borrowed entries with payment modes and reminders.",
    badge: "Cash & ledger",
    accent: "bg-emerald-600 text-white",
    icon: "Coins",
    resource: "money_transactions",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "mobile_number", label: "Mobile", type: "tel" },
      {
        key: "transaction_type",
        label: "Type",
        type: "select",
        required: true,
        options: [
          { label: "Income (आय)", value: "income" },
          { label: "Expense (खर्च)", value: "expense" },
          { label: "Lent (दिलं)", value: "lent" },
          { label: "Borrowed (घेतलं)", value: "borrowed" },
        ],
      },
      { key: "amount", label: "Amount", type: "number", step: "0.01", required: true },
      { key: "payment_mode", label: "Payment mode", type: "select", options: paymentModeOptions },
      { key: "bank_name", label: "Bank name", type: "text" },
      { key: "account_number", label: "Account number", type: "text" },
      { key: "transaction_id", label: "Reference / TXN ID", type: "text" },
      { key: "date", label: "Date", type: "date" },
      { key: "due_date", label: "Due date", type: "date" },
      { key: "status", label: "Status", type: "select", options: [ { label: "Pending", value: "pending" }, { label: "Paid", value: "paid" } ] },
      { key: "reminder_at", label: "Reminder at", type: "datetime-local" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      { key: "transaction_type", label: "Type", type: "badge" },
      { key: "name", label: "Name" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "payment_mode", label: "Mode" },
      { key: "date", label: "Date", type: "date" },
      { key: "status", label: "Status", type: "badge" },
    ],
    summaries: [
      { label: "Income", type: "sum", field: "amount", prefix: "₹", filter: { transaction_type: "income" } },
      { label: "Expense", type: "sum", field: "amount", prefix: "₹", filter: { transaction_type: "expense" } },
      { label: "Balance", type: "computed", tone: "accent" },
    ],
    emptyState: "Add transactions to manage cash flow and reminders.",
  },
  {
    slug: "advance-bookings",
    section: "Sales",
    title: "Advance Booking Memo",
    subtitle: "",
    badge: "Client critical",
    accent: "bg-accent text-white",
    icon: "ReceiptText",
    resource: "advance-bookings",
    fields: [
      { key: "customer_name", label: "Buyer name", type: "text", required: true },
      { key: "seller_name", label: "Seller name", type: "text" },
      { key: "customer_phone", label: "Mobile", type: "tel" },
      { key: "customer_email", label: "Email", type: "email" },
      { key: "plot_id", label: "Plot ID", type: "number", step: "1" },
      { key: "project_id", label: "Project Info", type: "project_select", required: true },
      { key: "village", label: "Village", type: "text", required: true },
      { key: "survey_number", label: "Survey number", type: "text", required: true },
      { key: "area_sqft", label: "Area (sq.ft.)", type: "number", step: "0.01" },
      { key: "total_amount", label: "Total amount", type: "number", step: "0.01", required: true },
      { key: "advance_amount", label: "Advance amount", type: "number", step: "0.01", required: true },
      { key: "payment_mode", label: "Payment mode", type: "select", options: paymentModeOptions },
      { key: "payment_at", label: "Payment date & time", type: "datetime-local" },
      { key: "gst_enabled", label: "GST enabled", type: "checkbox" },
      { key: "gst_number", label: "GST number", type: "text" },
      { key: "customer_signature_url", label: "Buyer Signature", type: "image" },
      { key: "company_signature_url", label: "Company Signature", type: "image" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      { key: "memo_number", label: "Memo" },
      { key: "customer_name", label: "Buyer" },
      { key: "seller_name", label: "Seller" },
      { key: "village", label: "Village" },
      { key: "advance_amount", label: "Advance", type: "currency" },
      { key: "remaining_amount", label: "Remaining", type: "currency" },
      { key: "message_status", label: "Message", type: "badge" },
    ],
    summaries: [
      { label: "Bookings", type: "count", tone: "accent" },
      { label: "Advance in", type: "sum", field: "advance_amount", prefix: "₹" },
    ],
    emptyState: "Create booking memos to issue PDFs and send branded confirmations automatically.",
  },
  {
    slug: "advance-agreements",
    section: "Sales",
    title: "Advance Agreement Memo",
    subtitle: "Developer-side purchase advance entries with refundable rules and agreement duration.",
    badge: "Land buying",
    accent: "bg-white text-black",
    icon: "FileSignature",
    resource: "advance-agreements",
    fields: [
      { key: "owner_name", label: "Owner / broker name", type: "text", required: true },
      { key: "owner_phone", label: "Phone", type: "tel" },
      { key: "owner_email", label: "Email", type: "email" },
      { key: "plot_id", label: "Plot ID", type: "number", step: "1" },
      { key: "project_id", label: "Project Info", type: "project_select", required: true },
      { key: "village", label: "Village", type: "text", required: true },
      { key: "survey_number", label: "Survey number", type: "text", required: true },
      { key: "area_sqft", label: "Area (sq.ft.)", type: "number", step: "0.01" },
      { key: "total_amount", label: "Total amount", type: "number", step: "0.01", required: true },
      { key: "paid_amount", label: "Paid amount", type: "number", step: "0.01", required: true },
      { key: "payment_mode", label: "Payment mode", type: "select", options: paymentModeOptions },
      { key: "refundable", label: "Refundable", type: "checkbox" },
      { key: "agreement_duration_days", label: "Agreement duration (days)", type: "number", step: "1" },
      { key: "conditions_text", label: "Conditions", type: "textarea" },
      { key: "inspection_rights", label: "Inspection rights", type: "textarea" },
      { key: "agreement_at", label: "Agreement date & time", type: "datetime-local" },
      { key: "owner_photo_url", label: "Owner Photo", type: "image" },
      { key: "owner_signature_url", label: "Owner Signature", type: "image" },
      { key: "company_signature_url", label: "Company Signature", type: "image" },
    ],
    columns: [
      { key: "owner_name", label: "Owner / Broker" },
      { key: "village", label: "Village" },
      { key: "paid_amount", label: "Advance Paid", type: "currency" },
      { key: "remaining_amount", label: "Remaining", type: "currency" },
      { key: "refundable", label: "Refundable", type: "boolean" },
      { key: "agreement_duration_days", label: "Days", type: "number" },
    ],
    summaries: [
      { label: "Agreements", type: "count", tone: "accent" },
      { label: "Advance out", type: "sum", field: "paid_amount", prefix: "₹" },
    ],
    emptyState: "Add land-owner agreements to produce short purchase-side memos.",
  },
  {
    slug: "agents",
    section: "Teams",
    title: "Agent Management",
    subtitle: "Profiles, bank details, signatures, and commission tracking by month or project.",
    badge: "Commission ready",
    accent: "bg-accent text-white",
    icon: "Users",
    resource: "agents",
    fields: [
      { key: "name", label: "Agent name", type: "text", required: true },
      { key: "phone", label: "Phone", type: "tel" },
      { key: "email", label: "Email", type: "email" },
      { key: "photo_url", label: "Photo / Image", type: "image" },
      { key: "signature_url", label: "Signature", type: "image" },
      { key: "bank_name", label: "Bank name", type: "text" },
      { key: "account_number", label: "Account number", type: "text" },
      { key: "ifsc_code", label: "IFSC", type: "text" },
      { key: "upi_id", label: "UPI ID", type: "text" },
      { key: "commission_percent", label: "Commission (%)", type: "number", step: "0.01" },
      { key: "commission_fixed", label: "Fixed commission", type: "number", step: "0.01" },
      { key: "address", label: "Address", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: statusOptions },
    ],
    columns: [
      { key: "name", label: "Agent" },
      { key: "phone", label: "Phone" },
      { key: "bank_name", label: "Bank" },
      { key: "commission_percent", label: "Commission %", type: "number" },
      { key: "status", label: "Status", type: "badge" },
    ],
    summaries: [
      { label: "Agents", type: "count", tone: "accent" },
      { label: "Active", type: "count" },
    ],
    emptyState: "Add agents to start project-wise and monthly commission reporting.",
  },
  {
    slug: "employees",
    section: "Teams",
    title: "Employee Management",
    subtitle: "Staff profiles, salary basis, and active field or office operations.",
    badge: "HR base",
    accent: "bg-black text-white",
    icon: "BriefcaseBusiness",
    resource: "employees",
    fields: [
      { key: "name", label: "Employee name", type: "text", required: true },
      { key: "role_title", label: "Role title", type: "text", required: true },
      { key: "phone", label: "Phone", type: "tel" },
      { key: "email", label: "Email", type: "email" },
      {
        key: "salary_type",
        label: "Salary type",
        type: "select",
        options: [
          { label: "Monthly", value: "monthly" },
          { label: "Daily", value: "daily" },
          { label: "Contract", value: "contract" },
        ],
      },
      { key: "monthly_salary", label: "Salary / rate", type: "number", step: "0.01" },
      { key: "joining_date", label: "Joining date", type: "date" },
      { key: "photo_url", label: "Photo / Image", type: "image" },
      { key: "signature_url", label: "Signature", type: "image" },
      { key: "address", label: "Address", type: "textarea" },
      { key: "location_tracking_enabled", label: "Location attendance", type: "checkbox" },
      { key: "status", label: "Status", type: "select", options: statusOptions },
    ],
    columns: [
      { key: "name", label: "Employee" },
      { key: "role_title", label: "Role" },
      { key: "salary_type", label: "Salary type", type: "badge" },
      { key: "monthly_salary", label: "Rate", type: "currency" },
      { key: "status", label: "Status", type: "badge" },
    ],
    summaries: [
      { label: "Employees", type: "count", tone: "accent" },
      { label: "Monthly payroll", type: "sum", field: "monthly_salary", prefix: "₹" },
    ],
    emptyState: "Create the employee base before attendance and salary tracking.",
  },
  {
    slug: "attendance",
    section: "Teams",
    title: "Attendance",
    subtitle: "Location-ready attendance entries with check-in and check-out timestamps.",
    badge: "Field attendance",
    accent: "bg-white text-black",
    icon: "MapPinCheckInside",
    resource: "attendance",
    fields: [
      { key: "employee_id", label: "Employee ID", type: "number", step: "1", required: true },
      { key: "attendance_date", label: "Attendance date", type: "date", required: true },
      { key: "check_in_at", label: "Check in", type: "datetime-local" },
      { key: "check_out_at", label: "Check out", type: "datetime-local" },
      { key: "location_label", label: "Location", type: "text" },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: [
          { label: "Present", value: "present" },
          { label: "Absent", value: "absent" },
          { label: "Half day", value: "half-day" },
          { label: "Leave", value: "leave" },
        ],
      },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      { key: "employee_id", label: "Employee ID", type: "number" },
      { key: "attendance_date", label: "Date", type: "date" },
      { key: "location_label", label: "Location" },
      { key: "status", label: "Status", type: "badge" },
    ],
    summaries: [
      { label: "Entries", type: "count", tone: "accent" },
      { label: "Employees covered", type: "unique", field: "employee_id" },
    ],
    emptyState: "Log daily attendance to build salary and performance reports.",
  },
  {
    slug: "salary-tracker",
    section: "Teams",
    title: "Salary Tracker",
    subtitle: "Monthly payroll entries with bonus, deductions, and payment state.",
    badge: "Payroll",
    accent: "bg-accent text-white",
    icon: "WalletCards",
    resource: "salaries",
    fields: [
      { key: "employee_id", label: "Employee ID", type: "number", step: "1", required: true },
      { key: "month_label", label: "Month label", type: "text", required: true, placeholder: "2026-05" },
      { key: "base_amount", label: "Base amount", type: "number", step: "0.01", required: true },
      { key: "bonus_amount", label: "Bonus", type: "number", step: "0.01" },
      { key: "deduction_amount", label: "Deduction", type: "number", step: "0.01" },
      { key: "paid_at", label: "Paid at", type: "datetime-local" },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: [
          { label: "Pending", value: "pending" },
          { label: "Paid", value: "paid" },
          { label: "Partially paid", value: "partial" },
        ],
      },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      { key: "employee_id", label: "Employee ID", type: "number" },
      { key: "month_label", label: "Month" },
      { key: "net_amount", label: "Net", type: "currency" },
      { key: "status", label: "Status", type: "badge" },
      { key: "paid_at", label: "Paid at", type: "date" },
    ],
    summaries: [
      { label: "Payroll rows", type: "count", tone: "accent" },
      { label: "Net salary", type: "sum", field: "net_amount", prefix: "₹" },
    ],
    emptyState: "Add payroll periods to track salary obligations and payouts.",
  },
  {
    slug: "performance",
    section: "Teams",
    title: "Performance Tracking",
    subtitle: "Scored reviews, highlights, and concerns for field teams and office staff.",
    badge: "Top performer",
    accent: "bg-black text-white",
    icon: "TrendingUp",
    resource: "performances",
    fields: [
      { key: "employee_id", label: "Employee ID", type: "number", step: "1", required: true },
      { key: "review_period", label: "Review period", type: "text", required: true },
      { key: "score", label: "Score", type: "number", step: "0.1", required: true },
      { key: "highlights", label: "Highlights", type: "textarea" },
      { key: "concerns", label: "Concerns", type: "textarea" },
    ],
    columns: [
      { key: "employee_id", label: "Employee ID", type: "number" },
      { key: "review_period", label: "Period" },
      { key: "score", label: "Score", type: "number" },
      { key: "created_at", label: "Logged", type: "date" },
    ],
    summaries: [
      { label: "Reviews", type: "count", tone: "accent" },
      { label: "Employees reviewed", type: "unique", field: "employee_id" },
    ],
    emptyState: "Track performance to identify top performers and salary context.",
  },
  {
    slug: "communications",
    section: "Communication",
    title: "Communication Log",
    subtitle: "Follow-ups, reminder dates, and festival or confirmation messaging with branded voice.",
    badge: "WhatsApp / Email",
    accent: "bg-accent text-white",
    icon: "MessagesSquare",
    resource: "communication-logs",
    fields: [
      { key: "related_type", label: "Related type", type: "text", placeholder: "booking / client / agent" },
      { key: "related_id", label: "Related ID", type: "number", step: "1" },
      { key: "contact_name", label: "Contact name", type: "text", required: true },
      { key: "contact_phone", label: "Phone", type: "tel" },
      { key: "contact_email", label: "Email", type: "email" },
      {
        key: "channel",
        label: "Channel",
        type: "select",
        options: [
          { label: "WhatsApp", value: "whatsapp" },
          { label: "Email", value: "email" },
          { label: "Call", value: "call" },
          { label: "SMS", value: "sms" },
        ],
      },
      {
        key: "style",
        label: "Style",
        type: "select",
        options: festivalStyles.map((style) => ({
          label: style.label,
          value: style.value,
        })),
      },
      { key: "subject", label: "Subject", type: "text" },
      { key: "body", label: "Message body", type: "textarea", required: true },
      {
        key: "direction",
        label: "Direction",
        type: "select",
        options: [
          { label: "Outbound", value: "outbound" },
          { label: "Inbound", value: "inbound" },
        ],
      },
      { key: "sent_at", label: "Sent at", type: "datetime-local" },
      { key: "follow_up_at", label: "Follow-up date", type: "datetime-local" },
      { key: "reminder_at", label: "Reminder date", type: "datetime-local" },
      { key: "status", label: "Status", type: "select", options: statusOptions },
    ],
    columns: [
      { key: "contact_name", label: "Contact" },
      { key: "channel", label: "Channel", type: "badge" },
      { key: "style", label: "Style", type: "badge" },
      { key: "status", label: "Status", type: "badge" },
      { key: "follow_up_at", label: "Follow-up", type: "date" },
    ],
    summaries: [
      { label: "Logs", type: "count", tone: "accent" },
      { label: "Channels", type: "unique", field: "channel" },
    ],
    emptyState: "Track calls, reminders, and festive campaigns in one history.",
  },
  {
    slug: "finance",
    section: "Finance",
    title: "Finance & GST",
    subtitle: "Income, expense, GST on or off, and bill split for monthly financial reporting.",
    badge: "GST module",
    accent: "bg-white text-black",
    icon: "BadgeIndianRupee",
    resource: "finance-entries",
    fields: [
      { key: "project_id", label: "Project Info", type: "project_select", required: true },
      { key: "category", label: "Category", type: "text", required: true },
      {
        key: "entry_type",
        label: "Entry type",
        type: "select",
        required: true,
        options: [
          { label: "Income", value: "income" },
          { label: "Expense", value: "expense" },
        ],
      },
      { key: "subcategory", label: "Subcategory", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "amount", label: "Amount", type: "number", step: "0.01", required: true },
      { key: "gst_enabled", label: "GST enabled", type: "checkbox" },
      { key: "gst_rate", label: "GST rate (%)", type: "number", step: "0.01" },
      { key: "bill_type", label: "Bill type", type: "select", options: gstBillOptions },
      { key: "payment_mode", label: "Payment mode", type: "select", options: paymentModeOptions },
      { key: "entry_date", label: "Entry date", type: "date" },
      { key: "reference_no", label: "Reference no.", type: "text" },
      { key: "vendor_name", label: "Vendor / party", type: "text" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      { key: "entry_type", label: "Type", type: "badge" },
      { key: "category", label: "Category" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "gst_amount", label: "GST", type: "currency" },
      { key: "bill_type", label: "Bill", type: "badge" },
      { key: "entry_date", label: "Date", type: "date" },
    ],
    summaries: [
      { label: "Finance rows", type: "count", tone: "accent" },
      { label: "Gross amount", type: "sum", field: "amount", prefix: "₹" },
    ],
    emptyState: "Start monthly finance reporting with GST-aware entries.",
  },
  {
    slug: "construction",
    section: "Sites",
    title: "Construction Management",
    subtitle: "Material, labor, contractor, engineer, and income entries for site-wise profitability.",
    badge: "Construction accounting",
    accent: "bg-accent text-white",
    icon: "Hammer",
    resource: "construction-entries",
    fields: [
      { key: "site_id", label: "Site ID", type: "number", step: "1", required: true },
      {
        key: "category",
        label: "Category",
        type: "select",
        required: true,
        options: [
          { label: "Material", value: "material" },
          { label: "Labor", value: "labor" },
          { label: "Contractor", value: "contractor" },
          { label: "Engineer", value: "engineer" },
          { label: "Other", value: "other" },
          { label: "Income", value: "income" },
        ],
      },
      { key: "description", label: "Description", type: "textarea", required: true },
      { key: "quantity", label: "Quantity", type: "number", step: "0.01" },
      { key: "rate", label: "Rate", type: "number", step: "0.01" },
      { key: "amount", label: "Amount", type: "number", step: "0.01" },
      { key: "supplier_name", label: "Supplier / contractor", type: "text" },
      { key: "bill_number", label: "Bill number", type: "text" },
      { key: "payment_mode", label: "Payment mode", type: "select", options: paymentModeOptions },
      { key: "entry_date", label: "Entry date", type: "date" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      { key: "site_id", label: "Site ID", type: "number" },
      { key: "category", label: "Category", type: "badge" },
      { key: "supplier_name", label: "Supplier" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "entry_date", label: "Date", type: "date" },
    ],
    summaries: [
      { label: "Site rows", type: "count", tone: "accent" },
      { label: "Construction value", type: "sum", field: "amount", prefix: "₹" },
    ],
    emptyState: "Capture construction spend and income for cost vs sale reporting.",
  },
  {
    slug: "development-sites",
    section: "Sites",
    title: "Development Site Control",
    subtitle: "Track JCB, tractor, damper, labor, and income activity with site-name-based records, auto calculations, and field-ready work slips.",
    badge: "Development operations",
    accent: "bg-black text-white",
    icon: "HardHat",
    resource: "development-entries",
    fields: [
      {
        key: "site_name",
        label: "Site Name",
        type: "text",
        required: true,
        placeholder: "Type the site name; the linked site master will be created automatically.",
      },
      { key: "entry_date", label: "Work Date", type: "date", required: true },
      {
        key: "category",
        label: "Category",
        type: "select",
        required: true,
        options: [
          { label: "JCB", value: "jcb" },
          { label: "Tractor", value: "tractor" },
          { label: "Damper", value: "damper" },
          { label: "Labor", value: "labor" },
          { label: "Misc", value: "misc" },
          { label: "Income", value: "income" },
        ],
      },
      { key: "jcb_number", label: "JCB Number", type: "text", showWhen: { category: "jcb" } },
      { key: "tractor_number", label: "Tractor Number", type: "text", showWhen: { category: "tractor" } },
      { key: "damper_number", label: "Damper Number", type: "text", showWhen: { category: "damper" } },
      { key: "owner_name", label: "Owner Name", type: "text", showWhen: { category: ["jcb", "tractor", "damper"] } },
      { key: "driver_name", label: "Driver Name", type: "text", showWhen: { category: "damper" } },
      { key: "mobile_number", label: "Mobile Number", type: "tel", showWhen: { category: ["tractor", "damper"] } },
      { key: "rent_type", label: "Rent Type", type: "select", options: tractorRentOptions, showWhen: { category: "tractor" } },
      { key: "amount_mode", label: "Rent Type", type: "select", options: damperAmountModeOptions, showWhen: { category: "damper" } },
      {
        key: "work_type",
        label: "Work Type",
        type: "select",
        options: [
          { label: "Soil Transport", value: "soil_transport" },
          { label: "Murum", value: "murum" },
          { label: "Sand", value: "sand" },
          { label: "Metal", value: "metal" },
          { label: "Debris", value: "debris" },
        ],
        showWhen: { category: "damper" },
      },
      { key: "construction_material", label: "Construction Material", type: "text", showWhen: { category: "damper" } },
      {
        key: "start_date",
        label: "Start Date",
        type: "date",
        showWhen: [
          { category: "tractor", rent_type: "daily" },
          { category: "damper", amount_mode: "daily" },
        ],
      },
      {
        key: "end_date",
        label: "End Date",
        type: "date",
        showWhen: [
          { category: "tractor", rent_type: "daily" },
          { category: "damper", amount_mode: "daily" },
        ],
      },
      {
        key: "total_days",
        label: "Total Days",
        type: "number",
        step: "0.01",
        readOnly: true,
        showWhen: [
          { category: "tractor", rent_type: "daily" },
          { category: "damper", amount_mode: "daily" },
        ],
      },
      {
        key: "start_time",
        label: "Start Time",
        type: "time",
        showWhen: [
          { category: "jcb" },
          { category: "tractor", rent_type: "hourly" },
          { category: "damper" },
        ],
      },
      {
        key: "stop_time",
        label: "Stop Time",
        type: "time",
        showWhen: [
          { category: "jcb" },
          { category: "tractor", rent_type: "hourly" },
          { category: "damper" },
        ],
      },
      {
        key: "total_hours",
        label: "Total Hours",
        type: "number",
        step: "0.01",
        readOnly: true,
        showWhen: [
          { category: "jcb" },
          { category: "tractor", rent_type: "hourly" },
          { category: "damper", amount_mode: "per_hour" },
        ],
      },
      {
        key: "rate_per_hour",
        label: "Rate Per Hour",
        type: "number",
        step: "0.01",
        showWhen: [
          { category: "jcb" },
          { category: "tractor", rent_type: "hourly" },
          { category: "damper", amount_mode: "per_hour" },
        ],
      },
      {
        key: "rate_per_day",
        label: "Rate Per Day",
        type: "number",
        step: "0.01",
        showWhen: [
          { category: "tractor", rent_type: "daily" },
          { category: "damper", amount_mode: "daily" },
        ],
      },
      { key: "total_trips", label: "Total Trips", type: "number", step: "1", showWhen: { category: "damper" } },
      { key: "rate_per_trip", label: "Rate Per Trip", type: "number", step: "0.01", showWhen: { category: "damper", amount_mode: "per_trip" } },
      { key: "advance_diesel", label: "Advance Diesel", type: "number", step: "0.01", showWhen: { category: ["jcb", "tractor", "damper"] } },
      { key: "diesel_given", label: "Diesel Given", type: "number", step: "0.01", showWhen: { category: "damper" } },
      { key: "diesel_cost", label: "Diesel Cost", type: "number", step: "0.01", showWhen: { category: "damper" } },
      { key: "amount", label: "Total Amount", type: "number", step: "0.01", readOnly: true },
      { key: "advance_paid", label: "Advance Paid", type: "number", step: "0.01", showWhen: { category: ["jcb", "tractor", "damper"] } },
      { key: "remaining_amount", label: "Remaining Amount", type: "number", step: "0.01", readOnly: true, showWhen: { category: ["jcb", "tractor", "damper"] } },
      { key: "payment_status", label: "Payment Status", type: "select", options: paymentStatusOptions, showWhen: { category: ["tractor", "damper"] } },
      { key: "loading_point", label: "Loading Point", type: "text", showWhen: { category: "damper" } },
      { key: "unloading_point", label: "Unloading Point", type: "text", showWhen: { category: "damper" } },
      { key: "work_location", label: "Work Location", type: "text", showWhen: { category: ["jcb", "tractor", "damper"] } },
      { key: "gps_location", label: "GPS Location", type: "text", showWhen: { category: ["jcb", "tractor", "damper"] } },
      { key: "work_description", label: "Work Description", type: "textarea", showWhen: { category: ["tractor", "damper"] } },
      { key: "working_photo_url", label: "Working Photo", type: "image", showWhen: { category: ["jcb", "tractor", "damper"] } },
      { key: "before_photo_url", label: "Before Photo", type: "image", showWhen: { category: "jcb" } },
      { key: "after_photo_url", label: "After Photo", type: "image", showWhen: { category: "jcb" } },
      { key: "signature_url", label: "Signature", type: "image", showWhen: { category: ["tractor", "damper"] } },
      { key: "description", label: "Description", type: "textarea", showWhen: { category: ["labor", "misc", "income"] } },
      { key: "quantity", label: "Quantity", type: "number", step: "0.01", showWhen: { category: ["labor", "misc", "income"] } },
      { key: "rate", label: "Rate", type: "number", step: "0.01", showWhen: { category: ["labor", "misc", "income"] } },
      { key: "vendor_name", label: "Vendor", type: "text", showWhen: { category: ["labor", "misc", "income"] } },
      { key: "bill_number", label: "Bill Number", type: "text", showWhen: { category: ["labor", "misc", "income"] } },
      { key: "payment_mode", label: "Payment Mode", type: "select", options: paymentModeOptions, showWhen: { category: ["labor", "misc", "income"] } },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      { key: "site_name", label: "Site Name" },
      { key: "work_type", label: "Work Type" },
      { key: "category", label: "Category", type: "badge" },
      { key: "owner_name", label: "Owner" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "remaining_amount", label: "Pending", type: "currency" },
      { key: "entry_date", label: "Date", type: "date" },
    ],
    summaries: [
      { label: "Entries", type: "count", tone: "accent" },
      { label: "Development value", type: "sum", field: "amount", prefix: "₹" },
    ],
    emptyState: "Track machine work, trips, diesel, and balances site by site with automatic hours, days, and amount calculations.",
  },
  {
    slug: "documents",
    section: "Vault",
    title: "Dast Document Vault",
    subtitle: "Plot document management for buyer, seller, witness, identifier, and land-paper workflows with print-ready export settings.",
    badge: "Smart print vault",
    accent: "bg-white text-black",
    icon: "FolderLock",
    resource: "document-folders",
    fields: [
      { key: "folder_code", label: "Dast Number", type: "text", readOnly: true },
      { key: "folder_label", label: "Auto Folder Label", type: "text", readOnly: true },
      { key: "project_id", label: "Project Name", type: "project_select", required: true },
      { key: "plot_number", label: "Plot Number", type: "text", required: true },
      { key: "buyer_name", label: "Buyer Name", type: "text", required: true },
      { key: "buyer_mobile_number", label: "Mobile Number", type: "tel" },
      { key: "buyer_aadhaar_number", label: "Buyer Aadhaar Number", type: "text" },
      { key: "buyer_pan_number", label: "Buyer PAN Number", type: "text" },
      { key: "seller_name", label: "Seller Name", type: "text" },
      { key: "seller_mobile_number", label: "Seller Mobile Number", type: "tel" },
      { key: "seller_aadhaar_number", label: "Seller Aadhaar Number", type: "text" },
      { key: "seller_pan_number", label: "Seller PAN Number", type: "text" },
      { key: "witness_1_name", label: "Witness 1 Name", type: "text" },
      { key: "witness_1_aadhaar_number", label: "Witness 1 Aadhaar", type: "text" },
      { key: "witness_2_name", label: "Witness 2 Name", type: "text" },
      { key: "witness_2_aadhaar_number", label: "Witness 2 Aadhaar", type: "text" },
      { key: "identifier_name", label: "Identifier Name", type: "text" },
      { key: "identifier_mobile_number", label: "Identifier Mobile", type: "tel" },
      { key: "identifier_aadhaar_number", label: "Identifier Aadhaar", type: "text" },
      { key: "print_layout", label: "Print Layout", type: "select", options: documentPrintLayoutOptions },
      { key: "aadhaar_layout", label: "Aadhaar Layout", type: "select", options: documentAadhaarLayoutOptions },
      { key: "page_orientation", label: "Page Orientation", type: "select", options: pageOrientationOptions },
      { key: "dpi_quality", label: "DPI Quality", type: "select", options: dpiQualityOptions },
      { key: "color_mode", label: "Color Mode", type: "select", options: [ { label: "Color", value: "color" }, { label: "Black & White", value: "bw" } ] },
      { key: "export_type", label: "Export Type", type: "select", options: exportTypeOptions },
      { key: "admin_lock", label: "Admin Lock", type: "checkbox" },
      { key: "is_hidden", label: "Hidden Folder", type: "checkbox" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      { key: "folder_code", label: "Dast No." },
      { key: "plot_number", label: "Plot Number" },
      { key: "buyer_name", label: "Buyer" },
      { key: "seller_name", label: "Seller" },
      { key: "buyer_mobile_number", label: "Mobile" },
      { key: "created_at", label: "Created", type: "date" },
    ],
    summaries: [
      { label: "Folders", type: "count", tone: "accent" },
      { label: "Projects", type: "unique", field: "project_id" },
    ],
    emptyState: "Create a Dast folder, save buyer and seller metadata, then upload secure supporting documents into the vault.",
  },
  {
    slug: "settings",
    section: "System",
    title: "Settings & Branding",
    subtitle: "Logo, theme colors, signature assets, invoice header, and company contact details.",
    badge: "Brand control",
    accent: "bg-accent text-white",
    icon: "Palette",
    fields: [],
    columns: [],
    summaries: [],
    emptyState: "Brand settings load from the company profile stored in the database.",
  },
];

export function getModuleConfig(slug: string) {
  return moduleCatalog.find((module) => module.slug === slug);
}

export function getModuleSections() {
  return moduleCatalog.reduce<Record<string, ModuleConfig[]>>((accumulator, module) => {
    accumulator[module.section] ??= [];
    accumulator[module.section].push(module);
    return accumulator;
  }, {});
}

export const protectedPaths: Array<ModuleSlug | "dashboard"> = [
  "dashboard",
  ...moduleCatalog.map((module) => module.slug),
];


